/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package practica;

import io.javalin.Javalin;
import java.sql.Date;
import practica.entidades.Estudiante;

import practica.API.Querys;
import practica.controladores.CrudTradicionalControlador;
import practica.controladores.PlantillasControlador;


public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        
        Javalin app = Javalin.create( config -> {
            config.staticFiles.add(staticFileConfig -> {
                staticFileConfig.hostedPath = "/";
                staticFileConfig.directory = "/publico";
            });
        })
        .start(8080);

        new CrudTradicionalControlador(app).aplicarRutas();
        new PlantillasControlador(app).aplicarRutas();



    }
}
